### ISSUE TITLE
pysolfc gondok

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#106]
1. nincs hangja
2. nincs lokalizáció
3. satöbbi

UBk3-on van hangja

**Comment by attuska** [comment]
Terminálban indítva van egy figyelemre méltó üzenet amit a pysolaudio.py fájl generál:
>attila@derp-x8664:~$ pysol
>Traceback (most recent call last):
>  File "/usr/lib/python3.10/site-packages/pysollib/pysolaudio.py", line 70, in connectServer
>   if self._connectServer():
>  File "/usr/lib/python3.10/site-packages/pysollib/pysolaudio.py", line 197, in _connectServer
>   r = self.cmd("protocol 6")
>  File "/usr/lib/python3.10/site-packages/pysollib/pysolaudio.py", line 193, in cmd
>    return self.audiodev.cmd(cmd)
>SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

Utána Googlézva ez python hibának tűnik!

**Comment by attuska** [comment]
https://github.com/uhulinux/ub-ubk4/commit/a8bb94147e26ef6cd77e61183f89c76cf0d0b301
A hangot megoldottam, a python3.pygame kell neki, a pysol-sound-server felesleges!
A fő gond megoldva, a többi nem érdekel, lezárom a hibajegyet.
