### ISSUE TITLE
lmms segmentation fault

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#122]

**Comment by attuska** [comment]
A gdb-ben ezt mondja:
Thread 1 "lmms" received signal SIGSEGV, Segmentation fault.
0x00007ffff68764fe in QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
(gdb) bt
#0  0x00007ffff68764fe in QCoreApplicationPrivate::sendThroughApplicationEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#1  0x00007ffff7962fe8 in QApplicationPrivate::notify_helper(QObject*, QEvent*)
    () from /usr/lib/libQt5Widgets.so.5
#2  0x00007ffff6876818 in QCoreApplication::notifyInternal2(QObject*, QEvent*)
    () from /usr/lib/libQt5Core.so.5
#3  0x00007ffff7995cc7 in QWidgetPrivate::setStyle_helper(QStyle*, bool) ()
   from /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff79a62da in QWidget::setParent(QWidget*, QFlags<Qt::WindowType>)
    () from /usr/lib/libQt5Widgets.so.5
#5  0x00007ffff79a66f6 in QWidgetPrivate::init(QWidget*, QFlags<Qt::WindowType>) () from /usr/lib/libQt5Widgets.so.5
#6  0x0000555555720c61 in MainWindow::MainWindow() ()
#7  0x000055555571596b in GuiApplication::GuiApplication() ()
#8  0x000055555563bf52 in main ()
(gdb)

**Comment by attuska** [comment]
Foltozni kellett. Mások már megoldották, már működik.
https://github.com/uhulinux/ub-ubk4/commit/a3bcef99e2b785759251422eb005d5d939bbe1ef
