### ISSUE TITLE
Vice: szegmentálási hiba

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#25]
Érvénytelen utasítás (core készült)
attila@attila-p5k:~$

**Comment by attuska** [comment]
Nvidia meghajtóval jó.
>Obtained OpenGL 3.2 context
	  Vendor: NVIDIA Corporation
	Renderer: GeForce 210/PCIe/SSE2
	 Version: 3.2.0 NVIDIA 340.108
	  Legacy: no
Direct GLX rendering context obtained
Swap control support. glXSwapIntervalMESA: 0 glXSwapIntervalEXT: 1 glXSwapIntervalSGI: 1
Created render thread 1
Render thread initialised
opening dynamic library libmp3lame.so failed!
ERROR setting up dynamic lame lib!
Sound: Available sound devices: pulse alsa dummy fs dump wav voc iff aiff mp3 soundmovie
Keyboard: Loading keymap `/usr/share/vice/C128/gtk3_sym.vkm'.
Keyboard: Warning - gtk3_sym.vkm:103: SHIFT-lock flag used but no !SHIFTL defined
Keyboard: Warning - gtk3_sym.vkm: !LCBM !VCBM !LCTRL !VCTRL !SHIFTL not defined.
Main CPU: starting at ($FFFC).
Main CPU: RESET.
Sound: Opened device `pulse', speed 44100Hz, fragment size 2,90ms, buffer size 26,12ms
reSID: MOS8580, filter on, sampling rate 44100Hz - resampling, pass to 19845Hz
Unit 8: RESET.

És működik, nincs szegmentálási hiba, a prompthoz ki kell lépni az emulátorból.

**Comment by attuska** [comment]
UBK3 alatt:
>Thread 7 "pool-x128" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffcadfe700 (LWP 90560)]
0x00007fffe1c1570d in ?? () from /usr/lib/dri/nouveau_dri.so
(gdb) bt
#0  0x00007fffe1c1570d in ?? () from /usr/lib/dri/nouveau_dri.so
#1  0x00007fffe1c158d9 in ?? () from /usr/lib/dri/nouveau_dri.so
#2  0x00007fffe1c15bea in ?? () from /usr/lib/dri/nouveau_dri.so
#3  0x00007fffe1f00733 in ?? () from /usr/lib/dri/nouveau_dri.so
#4  0x00007fffe1f00780 in ?? () from /usr/lib/dri/nouveau_dri.so
#5  0x00000000006057c9 in ?? ()
#6  0x00007ffff70755c4 in g_thread_pool_thread_proxy () from /usr/lib/libglib-2.0.so.0
#7  0x00007ffff7074e7d in g_thread_proxy () from /usr/lib/libglib-2.0.so.0
#8  0x00007ffff6917e45 in start_thread () from /lib/libpthread.so.0
#9  0x00007ffff684ed6f in clone () from /lib/libc.so.6
(gdb) 

Az x64 működik.

**Comment by attuska** [comment]
A frissített VICE szintén!
Ez mesa hiba lesz.

**Comment by attuska** [comment]
Rebuild után mindegyik érvénytelen utasításba botlik.

**Comment by attuska** [comment]
Lezárva, mert ez egy duplikátum.

**Comment by attuska** [comment]
Esetleg megy a c64 neki, ha a flathubról telepítettet használja.
