### ISSUE TITLE
pitivi nem indul

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#40]
**Ocsmány python**
>attila@attila-systemproductname:/usr/src/UHUBUILD/UB-UBK4$ pitivi
/usr/lib/python3.8/site-packages/numpy/ma/core.py:4466: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if self.shape is ():
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3.py", line 41, in <module>
    cursors.MOVE:          Gdk.Cursor.new_from_name(_display, "move"),
TypeError: constructor returned NULL
>
>The above exception was the direct cause of the following exception:
>
>Traceback (most recent call last):
  File "/bin/pitivi", line 172, in <module>
    _run_pitivi()
  File "/bin/pitivi", line 143, in _run_pitivi
    from pitivi import application
  File "/usr/lib/pitivi/python/pitivi/application.py", line 32, in <module>
    from pitivi.mainwindow import MainWindow
  File "/usr/lib/pitivi/python/pitivi/mainwindow.py", line 29, in <module>
    from pitivi.editorperspective import EditorPerspective
  File "/usr/lib/pitivi/python/pitivi/editorperspective.py", line 41, in <module>
    from pitivi.timeline.timeline import TimelineContainer
  File "/usr/lib/pitivi/python/pitivi/timeline/timeline.py", line 37, in <module>
    from pitivi.timeline.elements import Clip
  File "/usr/lib/pitivi/python/pitivi/timeline/elements.py", line 31, in <module>
    from matplotlib.backends.backend_gtk3cairo import FigureCanvasGTK3Cairo
  File "/usr/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3cairo.py", line 3, in <module>
    from . import backend_cairo, backend_gtk3
  File "/usr/lib/python3.8/site-packages/matplotlib/backends/backend_gtk3.py", line 50, in <module>
    raise ImportError(exc) from exc
ImportError: constructor returned NULL
attila@attila-systemproductname:/usr/src/UHUBUILD/UB-UBK4$

A régi verzióval is!

**Comment by rezso** [comment]
Kell nekünk ez a szutyok? Én legszívesebben kidobnám, a runsnakerun és a winpdb akármikkel együtt.

**Comment by attuska** [comment]
Ezt és a cuccait kidobtam, ha valakinek hiányzik, akkor majd jeltzi, akkor esetleg majd kinlódok vele.
Van még bőven videó szerkesztőnk és átalakítónk. (avidemux,handrbrake,mencoder,acidrip,cinellera,transmaggedon, satöbbi)
https://github.com/uhulinux/ub-ubk4/commit/9a3f1e13e63764a13963a6ef923f30d0b5b2a2cb
