### ISSUE TITLE
radiotray nem működik

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#51]
>attila@attila-systemproductname:~$ radiotray
Traceback (most recent call last):
  File "/bin/radiotray", line 8, in <module>
    from src import radiotray
ModuleNotFoundError: No module named 'src'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/radiotray/radiotray.py", line 10, in <module>
    from src.RadioTray import RadioTray
ModuleNotFoundError: No module named 'src'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
  File "/bin/radiotray", line 10, in <module>
    from radiotray import radiotray
  File "/usr/lib/python3.8/site-packages/radiotray/radiotray.py", line 12, in <module>
    from radiotray.RadioTray import RadioTray
  File "/usr/lib/python3.8/site-packages/radiotray/RadioTray.py", line 20, in <module>
    from .XmlDataProvider import XmlDataProvider
  File "/usr/lib/python3.8/site-packages/radiotray/XmlDataProvider.py", line 23, in <module>
    from gi.repository import Gtk
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "/usr/lib/python3.8/site-packages/gi/importer.py", line 145, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.8/site-packages/gi/overrides/__init__.py", line 118, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.8/site-packages/gi/overrides/Gtk.py", line 168, in <module>
    class Container(Gtk.Container, Widget):
  File "/usr/lib/python3.8/site-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gtk' object has no attribute 'Container'
attila@attila-systemproductname:~$

**Comment by attuska** [comment]
UBK3 jó.

**Comment by attuska** [comment]
A python3 függőségeit az UBK3 verzióira hozva nincs javulás.

**Comment by attuska** [comment]
Egy hasonló: https://gitlab.gnome.org/GNOME/pygobject/-/issues/423

**Comment by attuska** [comment]
>attila@attila-systemproductname:~$ export PYTHONPATH=$PYTHONPATH:/usr/bin/:/usr/lib/python3.8/site-packages/radiotray
attila@attila-systemproductname:~$ radiotray
Traceback (most recent call last):
  File "/bin/radiotray", line 10, in <module>
    from radiotray import radiotray
  File "/usr/lib/python3.8/site-packages/radiotray/radiotray.py", line 12, in <module>
    from radiotray.RadioTray import RadioTray
ModuleNotFoundError: No module named 'radiotray.RadioTray'; 'radiotray' is not a package
attila@attila-systemproductname:~$

**Comment by attuska** [comment]
A gi helyes verzójával jó lett! https://github.com/uhulinux/ub-ubk4/commit/e8bfd7c467fb3c18df74eed8fe469ecc0682e86d

**Comment by attuska** [comment]
Sziasztok!

Nem indul a radiotray, Ezt írja, ha terminálból indítom:

"
Traceback (most recent call last):
 File "/usr/lib/python3.10/site-packages/radiotray/radiotray.py", line 10, in <module>
   from src.RadioTray import RadioTray
ModuleNotFoundError: No module named 'src'
"

Előre is köszönöm a segítséget!

Török

**Comment by attuska** [comment]
Nem állok neki, mert a radiotray csak panelfüggő. Az XFCE, GNOME, PLASMA, LXDE satöbbi más panelt használ, nem MATE panel-t.

**Comment by rezso** [comment]
Akkor marad így.

**Comment by attuska** [comment]
Mehetne ez? https://github.com/ErikLethDanielsen/radiotray-q
Ez tán praktikusabb a python szörnyetegnél.
Kell neki qt lejátszó, meg internet, ami amúgyis fenn van.

Megcsináltam a csomagot, egyetlen binárisból áll.

Működik ott, ahol van normálisabb tálca. Kipróbálva: MATE, PLASMA-X, ICEWM, PEKWM, OPENBOX, FLUXBOX, JWM, LXDE, LXQT és XFCE alatt. GNOME mostani tálcáján nem jelenik meg, de ott speciális tálca van.

**Comment by attuska** [comment]
Ez is jó. https://github.com/coderholic/pyradio
Igaz, hogy python és nincs tálcája, de jól működik az MPAYER, VLC, vagy MPV backenddel:

**Comment by rezso** [comment]
Nekem mindegy, csak legyen valamilyen támogatása - fejlesztői vagy akár nagy disztró csomagolói.

**Comment by attuska** [comment]
Ha benne vagyok, próbálgatom a többit is, van belőle választék bőven de jobbára csak UBUNTUHOZ, de ahhoz meg aytana, meg appindicator kellene. A pythonokat is gyűlölöm, a qt5-ös a szimpatikusabb nekem, de az meg le van állva.

**Comment by attuska** [comment]
Belefáradtam.
Minden máshoz kellene libappindicator, de a libappindicator nem leli a pythonunkat. Nem lesz UBUNTU specifikus libappindicator csomagunk, mert egyedül a bzr forrást nem néztem, abból talán lehetne, mert Arch abból csinálja, de nincs nálunk bzr. A gentoo-t, fedorát is néztem, ott van más forrásból is, de nálunk mindegyik orra esik a python verzió észlelésében. A python split() a hiba okozója.

Az eddig nem működő radiotray csomagunkat kipróbáltam, most működik, szól, de van még hibaüzenet a terminálban, amit idemásolok. Lehet, hogy némelyik orvosolható, lehet, hogy nem is kell majd más helyette.
`attila@derp-x8664:~$ radiotray
Gnome Media Keys, Controls Radio Tray through keyboard multimedia keys, GnomeMediaKeysPlugin.py, Carlos Ribeiro
HelloWorld, This is a test plugin, HelloWorld.py, Carlos Ribeiro
started
Sleep Timer, Stops playing after a predefined time, SleepTimerPlugin.py, Carlos Ribeiro
History, Shows song history, HistoryPlugin.py, Carlos Ribeiro
Mate Media Keys, Controls Radio Tray through keyboard multimedia keys, MateMediaKeysPlugin.py, Ken
Notifications, Shows message notifications on the desktop, NotificationPlugin.py, Carlos Ribeiro
StationSwitcher, Allows cycling through stations, StationSwitcherPlugin.py, Mark F
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/radiotray/AudioPlayerGStreamer.py", line 163, in on_message
    self.eventManager.notify(EventManager.STATE_CHANGED, {'state':'playing', 'station':station})
  File "/usr/lib/python3.10/site-packages/radiotray/events/EventManager.py", line 46, in notify
    callback(data)
  File "/usr/lib/python3.10/site-packages/radiotray/NotificationManager.py", line 41, in on_state_changed
    self.eventManagerWrapper.notify(_('Radio Tray Playing'), station)
  File "/usr/lib/python3.10/site-packages/radiotray/events/EventMngNotificationWrapper.py", line 31, in notify
    self.eventManager.notify(self.eventManager.NOTIFICATION, {'title': title, 'message':message})
  File "/usr/lib/python3.10/site-packages/radiotray/events/EventManager.py", line 46, in notify
    callback(data)
  File "/usr/share/radiotray/plugins/NotificationPlugin.py", line 69, in on_notification
    self.notif.show()
gi.repository.GLib.GError: g-io-error-quark: Hiba a StartServiceByName hívásakor ehhez: org.freedesktop.Notifications: Az időkorlát elérve (24)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/radiotray/AudioPlayerGStreamer.py", line 196, in on_message
    self.eventManager.notify(EventManager.SONG_CHANGED, metadata)
  File "/usr/lib/python3.10/site-packages/radiotray/events/EventManager.py", line 46, in notify
    callback(data)
  File "/usr/lib/python3.10/site-packages/radiotray/NotificationManager.py", line 83, in on_song_changed
    self.eventManagerWrapper.notify(msgTitle, msg)
  File "/usr/lib/python3.10/site-packages/radiotray/events/EventMngNotificationWrapper.py", line 31, in notify
    self.eventManager.notify(self.eventManager.NOTIFICATION, {'title': title, 'message':message})
  File "/usr/lib/python3.10/site-packages/radiotray/events/EventManager.py", line 46, in notify
    callback(data)
  File "/usr/share/radiotray/plugins/NotificationPlugin.py", line 76, in on_notification
    self.notif.show()
gi.repository.GLib.GError: g-io-error-quark: Hiba a StartServiceByName hívásakor ehhez: org.freedesktop.Notifications: Az időkorlát elérve (24)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/radiotray/AudioPlayerGStreamer.py", line 196, in on_message
    self.eventManager.notify(EventManager.SONG_CHANGED, metadata)
  File "/usr/lib/python3.10/site-packages/radiotray/events/EventManager.py", line 46, in notify
    callback(data)
  File "/usr/lib/python3.10/site-packages/radiotray/NotificationManager.py", line 83, in on_song_changed
    self.eventManagerWrapper.notify(msgTitle, msg)
  File "/usr/lib/python3.10/site-packages/radiotray/events/EventMngNotificationWrapper.py", line 31, in notify
    self.eventManager.notify(self.eventManager.NOTIFICATION, {'title': title, 'message':message})
  File "/usr/lib/python3.10/site-packages/radiotray/events/EventManager.py", line 46, in notify
    callback(data)
  File "/usr/share/radiotray/plugins/NotificationPlugin.py", line 76, in on_notification
    self.notif.show()
gi.repository.GLib.GError: g-dbus-error-quark: Hiba a StartServiceByName hívásakor ehhez: org.freedesktop.Notifications: Process org.freedesktop.Notifications exited with status 1 (25)`

**Comment by rezso** [comment]
A libappindicator a bzr-ben is kb. 2 éves (https://bazaar.launchpad.net/~indicator-applet-developers/libappindicator/trunk/changes/298?start_revid=298), nyilván nem kezeli a python 3.10-et. Na meg tényleg ubuntus marhaság.
Az org.freedesktop.Notifications hívás pedig nem működik, mert ki lett dobva a notification-daemon csomag, mert nem volt függősége semminek.
Ennyit számít, hogy valami karbantartott-e, vagy sem.

**Comment by attuska** [comment]
Köszi! Megvan a notification-deamon csomag újra, feltelepítettem és a notification visszajelzések megszűntek.
Vagy visszarakom, de nekem szimpatikusabb lenne, ha ez az alapértelmezetten bekapcsolt, de kikapcsolható  plugin nem is létezne. Megkísérlem kiszedni belőle, ha már amúgy sem használjuk, hogy ne zavarjon. Lehet, hogy meg fog maradni ez a csomag és a radoiotray-qt jön még hozzá, amihez nem kell egy újabb csomag sem.

**Comment by attuska** [comment]
A radiotray-qt az szerintem kell majd valakinek, a radiotray-nál az alapértelmezetten bekapcsolt notification kikapcsolva, ha valaki mégis megteszi, ne reklamáljon. Az ikonja a mate tálcán nálam zavaró, de ettől még szól. A radiotray-qt ikonja már jó. Ez utóbbinak kell a qt médialejátszó, ez előbbinek vagy az mplayer, vagy a vlc, vagy az mpv.
Új csomag nem kell egyiknek sem.
A kommit: https://github.com/uhulinux/ub-ubk4/commit/44b440fc4f465d1fdcb29905dbb456a53080d330
Részemről kész, lezárom a hibajagyet újra.
