### ISSUE TITLE
kdegames python3 hibák

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#66]
Felfedeztem jó pár python3 runtime hibát.

**Comment by attuska** [comment]
attila@attila-systemproductname:~$ kajongg
Traceback (most recent call last):
  File "/bin/kajongg", line 20, in <module>
    from qt import QObject, QCommandLineParser, QCommandLineOption, Qt, QGuiApplication
  File "/usr/share/kajongg/qt.py", line 12, in <module>
    from qtpy import uic
ModuleNotFoundError: No module named 'qtpy'
attila@attila-systemproductname:~$ kajongg
Traceback (most recent call last):
  File "/bin/kajongg", line 20, in <module>
    from qt import QObject, QCommandLineParser, QCommandLineOption, Qt, QGuiApplication
  File "/usr/share/kajongg/qt.py", line 12, in <module>
    from qtpy import uic
  File "/usr/lib/python3.10/site-packages/qtpy/__init__.py", line 57, in <module>
    from packaging.version import parse
ModuleNotFoundError: No module named 'packaging'
attila@attila-systemproductname:~$ kajongg
C:  * Kajongg is not correctly installed: modules: No module named 'kajcsv'
ttila@attila-systemproductname:~$ kajonggserver
Traceback (most recent call last):
  File "/bin/kajonggserver", line 11, in <module>
    from server import kajonggServer
  File "/usr/share/kajongg/server.py", line 73, in <module>
    from servertable import ServerTable, ServerGame
  File "/usr/share/kajongg/servertable.py", line 31, in <module>
    from client import Client, Table
  File "/usr/share/kajongg/client.py", line 24, in <module>
    from game import PlayingGame
  File "/usr/share/kajongg/game.py", line 19, in <module>
    from kajcsv import CsvRow
ModuleNotFoundError: No module named 'kajcsv'
attila@attila-systemproductname:~$

**Comment by rezso** [comment]
A frissített, 22.04.1-es nem találja a meglévő python3-twisted csomagot. Kidobom, nem akarok ezzel szórakozni.
