### ISSUE TITLE
glxinfo bug?

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#81]
attila@derp-x8664:~$ glxinfo
name of display: :0
glxinfo: ../nptl/pthread_mutex_lock.c:428: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.
Félbeszakítva (core készült)
attila@derp-x8664:~$

**Comment by attuska** [comment]
gdb-ben:
(gdb) r
Starting program: /usr/bin/glxinfo 
name of display: :0
warning: File "/usr/lib/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
	add-auto-load-safe-path /usr/lib/libthread_db-1.0.so
line to your configuration file "/home/attila/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/home/attila/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
glxinfo: ../nptl/pthread_mutex_lock.c:428: __pthread_mutex_lock_full: Assertion `e != ESRCH || !robust' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff7990615 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7990615 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7979862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff7979747 in ?? () from /usr/lib/libc.so.6
#3  0x00007ffff7988bf6 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007ffff746d4c4 in ?? () from /usr/lib/libpthread.so.0
#5  0x00007ffff7b69a48 in ?? () from /usr/lib/libX11.so.6
#6  0x00007ffff7b722f1 in XQueryExtension () from /usr/lib/libX11.so.6
#7  0x00007ffff7b658a3 in XInitExtension () from /usr/lib/libX11.so.6
#8  0x00007ffff75aa471 in ?? () from /usr/lib/libGLX_mesa.so.0
#9  0x00007ffff75a20d4 in ?? () from /usr/lib/libGLX_mesa.so.0
#10 0x0000000000404f65 in ?? ()
#11 0x0000000000405333 in main ()
(gdb)

**Comment by attuska** [comment]
Találtam egy issiue-t
https://gitlab.freedesktop.org/mesa/demos/-/issues/27
