### ISSUE TITLE
youtub-downloader error

### ISSUE THREAD

**Issue by attuska** [uhulinux/ub-ubk4#92]
Python hiba (--verbose opcióval már bőbeszédűbb...:
`ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 815, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/youtube_dl/YoutubeDL.py", line 836, in __extract_info
    ie_result = ie.extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 534, in extract
    ie_result = self._real_extract(url)
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/youtube.py", line 1794, in _real_extract
    'uploader_id': self._search_regex(r'/(?:channel|user)/([^/?&#]+)', owner_profile_url, 'uploader id') if owner_profile_url else None,
  File "/usr/lib/python3.10/site-packages/youtube_dl/extractor/common.py", line 1012, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
`

**Comment by attuska** [comment]
Nyitott issue:
https://github.com/ytdl-org/youtube-dl/issues/31530

**Comment by rezso** [comment]
Nem meglepő. A google folyamatosan változtat a kódon, mert neki nem buli, hogy valaki letölti a videót, és így nem nézegeti a reklámokat. Ráadásul ez már több, mint 1 éves release.
Szerintem az smtube is nyűgös, ráadásul az qtwebkit-et használ, ami plusz problémás.

**Comment by attuska** [comment]
A gittből letöltött (nem az ősi release!) már szépen működik. Egyelőre csak nekem és nálam.
